package elaprendiz.ventanas;
import app.JStatusBar;
import elaprendiz.config.AppConfig;
import elaprendiz.util.AdminIFrame;
/**
 * @author Ferz
 */
public class MainWindow extends javax.swing.JFrame {

    
    private static IProveedores vntProveedores = null;
    private static ISimpleModelo vntModeloMarcaClase = null;
    private static IUsuario vntUsuario = null;
    private static IProducto vntProducto = null;
    private static ICompra vntCompra = null;
    
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        System.out.println(AppConfig.getUsuario().getNombre()+" - "+AppConfig.getUsuario().getApellidos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new JStatusBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 850));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jInternalFrame1.setTitle("Nota: JVentas");
        jInternalFrame1.setVisible(true);

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEditorPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n     Este Software se presenta como un demostrativo. su fin es educacional.\n     La persona que obtiene este software puede modifcar, adaptar o cambiar este software siempre y cuando incluya el nombre del autor original. ElAprendiz\n<ul>\n<li>\nSitio web: <a href=\"http://www.elaprendiz.net63.net\">www.elaprendiz.net63.net</a>\n</li>\n<li>\nPagina Facebook <a href=\"http://www.facebook.com/elaprendiz.sabe.algo\">http://www.facebook.com/elaprendiz.sabe.algo</a>\n</li>\n<li>\nCanal Youtube <a href=\"http://www.youtube.com/user/jleod7\">http://www.youtube.com/user/programadorBipolar</a>\n</li>\n<li>\nBlog <a href=\"http://www.javanoesdificil.blogspot.com\">http://www.javanoesdificil.blogspot.com</a>\n</li>\n</ul>\n    </p>\r\n  </body>\r\n</html>\r\n");
        jScrollPane1.setViewportView(jEditorPane1);

        jInternalFrame1.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        dp.add(jInternalFrame1);
        jInternalFrame1.setBounds(50, 30, 490, 310);

        getContentPane().add(dp);

        jPanel1.setPreferredSize(new java.awt.Dimension(549, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Producto");

        jMenuItem3.setText("Registrar Producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Registrar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Registrar Proveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem5.setText("Registrar Clase - Marcas - Modelos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.out.println("******");
       if(vntUsuario== null)
       {
           vntUsuario = new IUsuario(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntUsuario); 
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      System.out.println("******---");
       if(vntProveedores == null)
       {
           vntProveedores = new IProveedores(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntProveedores); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(vntProducto== null)
       {
           vntProducto = new IProducto(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntProducto);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(vntCompra== null)
       {
           vntCompra = new ICompra(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntCompra);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         if(vntModeloMarcaClase == null)
       {
           vntModeloMarcaClase = new ISimpleModelo(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntModeloMarcaClase); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
